### ISSUE TITLE
Problem detected while loading the contents of the Prefab file: 'Assets/MRTK.Tutorials.GettingStarted/Prefabs/PressableCylinderButton.prefab'.

### ISSUE THREAD

**Issue by CassiaVasconcelos** [MixedRealityToolkit/MixedRealityToolkit-Unity#481]
I am following the training to Hololens in "https://learn.microsoft.com/en-us/training/modules/get-started-with-object-interaction/", now i am in the buttons, and i have this error: Problem detected while loading the contents of the Prefab file: 'Assets/MRTK.Tutorials.GettingStarted/Prefabs/PressableCylinderButton.prefab'.

1. After importing the MRTK package 3.0.0, go to: Assets -> MRTK.Tutorials.GettingStarted -> Prefabs
2. Add "PressableCylinderButton" to the scene
3. See error

I thought there were supposed to be no problems with prefabs, was I missing something?

<img width="713" alt="image" src="https://github.com/microsoft/MixedRealityToolkit-Unity/assets/27698685/bac9e64e-a758-4ec5-bd71-63abf4f1fb8f">

- Unity Version 2023.1.12f1
- MRTK Version MRTK v3.0.0 GA

- HoloLens 2

**Comment by marlenaklein-msft** [comment]
Hi @CassiaVasconcelos, thanks for logging this. Could you confirm if you have the org.mixedrealitytoolkit.uxcomponents.noncanvas package in the project?

**Comment by CassiaVasconcelos** [comment]
Thank you! I don't have "no-canvas" just uxcomponentes:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/27698685/4f931d14-3b0e-4706-a97d-d508987bd6f1)

I didn't install it before because the project setup tutorial didn't indicate no-canvas (https://learn.microsoft.com/en-us/events/mixed-reality-dev-days/getting-started-with-your-first-mrtk3-project)
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/27698685/1b730b70-0bf9-447d-b8c9-e3122cd10cdf)

I just installed no-canvas, and I did "Reimport all" (Assets->Reimport All) I no longer have the import error, but also the object does not appear in the scene as a button and i get some initial errors (but they disappear when I clear)

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/27698685/6fd78cfa-96d4-441f-bbb7-735d91f5bb19)

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/27698685/3079d4f2-4232-45ac-8703-e019cefdd630)

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/27698685/b1aa77c2-da21-4700-af5d-e579e993144a)

**Comment by marlenaklein-msft** [comment]
@CassiaVasconcelos Ah that video might not align perfectly with these tutorials. I'd recommend going through the [introduction to MRTK](https://learn.microsoft.com/en-us/training/modules/learn-mrtk-tutorials/) and [object placement tutorials](https://learn.microsoft.com/en-us/training/modules/place-scene-objects/) to make sure everything is fully set up and ready for the getting started with object interaction tutorial.

Those errors about the controller model prefabs are unfortunately expected and they won't affect anything. The button should look something like this:

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/125413876/cf965e6d-d448-476c-a508-bae3264fe745)

It might prompt you to import TextMeshPro in order to show the text. If it helps, the final result of all of these tutorials can be found [here](https://github.com/microsoft/MixedRealityLearning/tree/development/MRTK3%20Tutorials) for comparison.

**Comment by CassiaVasconcelos** [comment]
@marlenaklein-msft  I was following the tutorial for the first time and there were several problems importing the 3.0 package, so I had been following the video just for the initial setup. I tried again now to create a new project and everything went well.

I really appreciate your time.

Thank you so much.

**Comment by marlenaklein-msft** [comment]
Great, glad to hear it! Let us know if you run into any other issues.
