### ISSUE TITLE
[BUG] Assets\QRCode\SpatialGraphNodeTracker.cs The type or namespace name 'Toolkit' does not exist in the namespace 'Microsoft.MixedReality' 

### ISSUE THREAD

**Issue by Xispeo** [MixedRealityToolkit/MixedRealityToolkit-Unity#590]
## Describe the bug

In a C# script, Unity fails to find  Microsoft.MixedReality.Toolkit.Utilities for QRCode detection and pose estimation

## To reproduce

From my functionnal project: I have removed MRTK 2.8.3 and added MRTK3:
- MRTK Core
- MRTK Diagnostics
- MRTK Extended Assets
- MRTK Graphics Tools
- MRTK Input
- MRTK Spatial Manipulation
- MRTK Standard Assets
- MRTK Tools
- MRTK UX Components
- MRTK UX Components (Non-Canvas)
- MRTK UX Core Scripts

I use Unity 2022.3.15 and QRCode detection.
Unity fails to find `Toolkit ` from `using Microsoft.MixedReality.Toolkit.Utilities;`
I found a thread talking about this problem on the web but it did not help me.

## Expected behavior

`Toolkit ` should get recognized by Unity

## Your setup (please complete the following information)

- Unity Version 2022.3.15
- MRTK 3.0.1

## Target platform (please complete the following information)

- HoloLens 2
- OpenXR

**Comment by marlenaklein-msft** [comment]
@Xispeo MRTK3 uses different namespaces than MRTK 2.8.3, and there is no Microsoft.MixedReality.Toolkit.Utilities in MRTK3. The old namespaces would need to be replaced with "using MixedReality.Toolkit;" (or "using MixedReality.Toolkit.Input;" etc. depending on what you are trying to use.)
	
Please be aware there are significant [differences](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-overview/architecture/mrtk-v2-to-v3) between MRTK2 and MRTK3. Porting a project over will require major changes to the project instead of just the replacement of MRTK2 packages with MRTK3 packages. 
	
It sounds like you may be using the [microsoft/MixedReality-QRCode-Sample](https://github.com/microsoft/MixedReality-QRCode-Sample/tree/main), which still uses MRTK2. @AMollis This may need to be updated to MRTK3.

**Comment by Xispeo** [comment]
@marlenaklein-msft Thank you for your answer. I am starting this porting task from MRTK 2.8.3 to MRTK 3.0.1 and have in mind the need to largely modify my project. Yes I am using https://github.com/microsoft/MixedReality-QRCode-Sample/tree/main for QR code pose estimation. I guess this is not possible for MRTK 2 & 3 to coexist in a project to that either I use an alternative solution or wait for MRTK3 to offer QRCode detection and pose estimation.

**Comment by AMollis** [comment]
This is outside of the MRTK3 project.   There is already a bug tracking updating the QR Code sample

- https://github.com/microsoft/MixedReality-QRCode-Sample/issues/20

However we recommend developers start migrating to the new AR Marker support in OpenXR.  Please see our sample here:

https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/tree/main/BasicSample/Assets/ARMarker

Note, to use AR Markers, you need to install the preview release of the Microsoft OpenXR runtime (version 113+)

**Comment by Xispeo** [comment]
Perfect, thank you !
