### ISSUE TITLE
[BUG] Assets\Scripts\SampleSceneHandMenu.cs(57,39): error CS0103: Assets\Scripts\SampleSceneHandMenu.cs(57,39): error CS0103: The name 'FindObjectUtility' does not exist in the current context

### ISSUE THREAD

**Issue by martatw** [MixedRealityToolkit/MixedRealityToolkit-Unity#595]
Hi,

I would like to download and run project. But I got compilation error : Assets\Scripts\SampleSceneHandMenu.cs(57,39): error CS0103: The name 'FindObjectUtility' does not exist in the current context

## To reproduce
 Unity 2021.3.21f1
 MRTK 3 v3.0.0

I just cloned the project, installed MRTK3 with MR Feature tools and changed platform to UWP.

**Comment by AMollis** [comment]
Hi @martatw,

Thank you for reporting this issue or requesting this feature. We appreciate your feedback and interest in MRTK3.

We have reviewed your issue or feature request and confirmed that it is valid. We have added it to our backlog and will prioritize it accordingly.

However, if you would like to speed up the process and contribute to the MRTK3 project, you are welcome to submit a Pull Request with your proposed fix or implementation. We would be happy to review your code and merge it into the main branch if it meets our quality standards.

Please let us know if you have any questions or need any assistance. Thank you for your support and collaboration.

Best regards,
The MRTK3 team

**Comment by cnathaus** [comment]
Hi,

I had the same problem using Unity 2021.3.21f1 and MRTK3. I'm a beginner at both so my description may not be very accurate: I tracked it down to the FindObjectUtility.cs somehow not being included in the PackageCache. I moved both the .cs and .meta file there from the core toolkit Utilities folder and now it works.

Would be interested to learn how to fix this if someone knows.

Best regards,
Christian

**Comment by haibo839455603** [comment]
Assets\Scripts\SampleSceneHandMenu.cs(57,39): error CS0103: The name 'FindObjectUtility' does not exist in the current context

I encountered the same problem

**Comment by slender9168** [comment]
Any fix?

**Comment by shaynie** [comment]
This is due to a version mismatch.  The "FindObjectUtility" was not introduced until version 3.1.0 of the org.mixedrealitytoolkit.core package.  Please try again with the latest release of the toolkit packages, and re-open the bug if you still encounter problems.

**Comment by whodat** [comment]
@shaynie reopen?

**Comment by shaynie** [comment]
@whodat Thanks for the report.  I just went through your repro steps and hit the same error.  Reopening.

**Comment by shaynie** [comment]
It turns out this is a bug in the Mixed Reality Feature Tool.  The second time it is run to install an additional package, it is not picking up that the dependencies of that new package are already installed with a higher version.  See this picture for when I added MRTK UX Components (non-canvas).  

![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/9615036/a8324a62-3bf0-4c44-ab39-283c10534c55)

Notice that It is asking you to install MRTK Core definitions 3.0.0 even though the project already has version 3.2.0 already installed.  The workaround is to clear the check marks in the Required Dependencies section and then import the package:
![image](https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/assets/9615036/ef564e0b-3f5c-4622-abcd-899ed0c35e79)

**Comment by whodat** [comment]
Thanks @shaynie! I was also getting a couple other errors due to version mismatches, and this explains it.
